name: trex
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: 0.4.3+2
  firebase_auth: 0.15.4
  firebase_analytics: 5.0.10
  cloud_firestore: ^0.13.0+1

  google_sign_in: 4.1.1
  meta: 1.1.8
  flutter_bloc: 3.1.0
  equatable: 1.0.2
  firebase_crashlytics: 0.1.2+5

  cupertino_icons: 0.1.3
  font_awesome_flutter: 8.5.0

dev_dependencies:

flutter:
  uses-material-design: true
  assets:
    - assets/
